# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
p "destroying Argonautes"
p "..."
Argonaute.destroy_all
p "#{Argonaute.count} destroyed"

p "creating new Argonautes"
p "..."

argonaute = Argonaute.create! name: "Jason", half_god: true, captain: true, notes: "The BOSS"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Acaste", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Actor", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Admète", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Amphiaraos", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Le Grand Ancée de Tégée", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Le Petit Ancée", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Argos le Thespien", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Ascalaphos d'Orchomène", half_god: true, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Astérios", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Atalante de Calydon", half_god: false, captain: false, notes: "The BOSS"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Augias", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Boutès d'Athènes", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Caenée le Lapithe", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Calaïs", half_god: true, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Canthos d'Eubée", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Castor", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Céphée", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Coronos", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Echion", half_god: true, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Erginos", half_god: false, captain: false, notes: "The BOSS"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Euphémos", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Euryale", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Eurydamas le Dolopien", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Héraclès de Tirynthe", half_god: true, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Hylas le Dryope", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Idas", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Idmon d'Argos", half_god: true, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Iphiclès", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Iphitos", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Laërte", half_god: false, captain: false, notes: "The BOSS"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Lyncée", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Mélampous de Pylos", half_god: true, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Méléagre de Calydon", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Mopsos le Lapithe", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Nauplios l'Argien", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Oïlée", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Orphée", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Palaemon", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Pelée le Myrmidon", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Pénéléos", half_god: false, captain: false, notes: "The BOSS"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Périclymènos de Pylos", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Phaléros", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Phanos", half_god: true, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Poeas", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Pollux", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Polyphème", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Staphylos", half_god: false, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
argonaute = Argonaute.create! name: "Thésée", half_god: true, captain: false, notes: "fils du roi Pélias"
p " #{argonaute.name} created !"
# argonaute = Argonaute.create! name: "Zétès", half_god: false, captain: false, notes: "fils du roi Pélias"
# p " #{argonaute.name} created !"
